Update main.lua
Qbox-project/qbx-vehiclekeys pull request #12
Opened 2023-09-13 19:35 UTC by MafewTM

## Description

Adds cache.ped properly instead of how it was done, adds a cache.playerId, and swaps GetHashKey to joaat. 

## Checklist

- [x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x ] My code fits the style guidelines.
- [x ] My PR fits the contribution guidelines.

2023-09-13 20:29 UTC, FjamZoo requested changes
Left some changes to do, overall looks good :)

2023-09-13 20:29 UTC, FjamZoo commented on client/main.lua
> +            if IsPedInAnyVehicle(cache.ped, false) and not IsHotwiring then
```suggestion
            if cache.vehicle and not IsHotwiring then
```
We want to use cache.vehicle here instead of using natives

2023-09-13 20:29 UTC, FjamZoo commented on client/main.lua
> +                local vehicle = GetVehiclePedIsIn(cache.ped)
```suggestion
                local vehicle = cache.vehicle
```

Either use cache.vehicle or rename all `vehicle` to cache.vehicle to make it look a little cleaner

2023-09-13 20:29 UTC, FjamZoo commented on client/main.lua
> +    if IsPedInAnyVehicle(cache.ped, false) then
```suggestion
    if cache.vehicle then
```

2023-09-13 20:29 UTC, FjamZoo commented on client/main.lua
> +        local vehicle = GetVehiclePedIsIn(cache.ped)
```suggestion
        local vehicle = cache.vehicle
```
Either use cache.vehicle or remove all `vehicle` and use cache.vehicle looks better

2023-09-13 21:19 UTC, MafewTM commented
> Left some changes to do, overall looks good :)

You are absolutely right. My bad. I've committed the changes

2023-09-14 01:00 UTC, Manason approved these changes

2023-09-17 15:13 UTC, merged